"""CarbonTransaction ORM model — calculated emissions from ERP operations.

A carbon transaction records the CO2e generated by a single operational event
(a purchase, a manufacturing run, an expense, a fleet trip). The emission is
**derived** as ``quantity x emission_factor.co2e_per_unit`` and, for
auto-generated rows, is kept read-only: any change to quantity or factor
re-derives it rather than allowing a hand-typed value to drift from the source.

Linking back to the originating ERP record
------------------------------------------
The source can be one of four different ERP tables (purchase / manufacturing /
expense / fleet), so a single SQL foreign key cannot point at all of them.
Instead the link is polymorphic: ``source_type`` + ``source_record_id`` identify
the exact originating row, with an optional human-readable ``source_reference``.
A concrete per-table FK can be added once those ERP models exist.

The emission factor link (``emission_factor_id``) points at the *specific
version* of the factor that was used, so recalculations stay reproducible even
after the factor is versioned forward (see :mod:`app.models.emission_factor`).
"""
from __future__ import annotations

import enum
from datetime import date

from sqlalchemy import (
    CheckConstraint,
    Date,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, Session, mapped_column, relationship, validates

from app.core.database import Base
from app.models.emission_factor import EmissionFactor


class SourceType(str, enum.Enum):
    """Which ERP subsystem the emission originated from."""

    PURCHASE = "purchase"
    MANUFACTURING = "manufacturing"
    EXPENSE = "expense"
    FLEET = "fleet"


class CreatedBy(str, enum.Enum):
    """Whether the transaction was auto-calculated or entered manually."""

    AUTO = "auto"
    MANUAL = "manual"


class TransactionStatus(str, enum.Enum):
    DRAFT = "draft"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"


class CarbonTransaction(Base):
    __tablename__ = "carbon_transactions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    department_id: Mapped[int | None] = mapped_column(
        ForeignKey("departments.id", ondelete="SET NULL"), nullable=True, index=True
    )
    department = relationship("Department")

    # Polymorphic link back to the originating ERP record.
    source_type: Mapped[SourceType] = mapped_column(
        Enum(SourceType, name="source_type"), nullable=False
    )
    source_record_id: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
    source_reference: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # The specific emission-factor version used for the calculation.
    emission_factor_id: Mapped[int] = mapped_column(
        ForeignKey("emission_factors.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    emission_factor = relationship("EmissionFactor")

    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    # Derived: quantity x emission_factor.co2e_per_unit. Read-only when AUTO.
    co2e: Mapped[float] = mapped_column(Float, nullable=False)

    transaction_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    created_by: Mapped[CreatedBy] = mapped_column(
        Enum(CreatedBy, name="created_by"), nullable=False, default=CreatedBy.AUTO
    )
    status: Mapped[TransactionStatus] = mapped_column(
        Enum(TransactionStatus, name="transaction_status"),
        nullable=False,
        default=TransactionStatus.DRAFT,
    )

    __table_args__ = (
        CheckConstraint("quantity >= 0", name="ck_carbon_txn_quantity_non_negative"),
        CheckConstraint("co2e >= 0", name="ck_carbon_txn_co2e_non_negative"),
        # Guard the derived invariant at the DB level for auto rows.
        CheckConstraint(
            "created_by <> 'auto' OR co2e = quantity * factor_value",
            name="ck_carbon_txn_auto_co2e_derived",
        ),
    )

    # Snapshot of the factor's per-unit value at calculation time, used both for
    # the derived-value DB check above and to keep co2e reproducible.
    factor_value: Mapped[float] = mapped_column(Float, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover - debug helper
        return (
            f"<CarbonTransaction {self.source_type.value}#{self.source_record_id} "
            f"{self.quantity}x{self.factor_value}={self.co2e} kgCO2e>"
        )

    @validates("quantity")
    def _recompute_on_quantity(self, key, value):
        """Re-derive CO2e whenever quantity changes on an auto transaction."""
        if getattr(self, "created_by", CreatedBy.AUTO) is CreatedBy.AUTO:
            if self.factor_value is not None and value is not None:
                self.co2e = value * self.factor_value
        return value

    def recalculate(self) -> float:
        """Recompute and store ``co2e`` from ``quantity`` x ``factor_value``."""
        self.co2e = self.quantity * self.factor_value
        return self.co2e

    @classmethod
    def record_auto(
        cls,
        db: Session,
        *,
        source_type: SourceType,
        quantity: float,
        transaction_date: date,
        factor_code: str | None = None,
        emission_factor: EmissionFactor | None = None,
        department_id: int | None = None,
        source_record_id: int | None = None,
        source_reference: str | None = None,
        status: TransactionStatus = TransactionStatus.CONFIRMED,
    ) -> "CarbonTransaction":
        """Create an auto-calculated transaction with a derived CO2e value.

        Provide either an explicit ``emission_factor`` version or a
        ``factor_code`` to resolve the factor in force on ``transaction_date``.
        CO2e is computed from the resolved factor and cannot be passed in.
        """
        if emission_factor is None:
            if factor_code is None:
                raise ValueError("Provide either emission_factor or factor_code")
            emission_factor = EmissionFactor.resolve(db, factor_code, transaction_date)
            if emission_factor is None:
                raise ValueError(
                    f"No active emission factor '{factor_code}' on {transaction_date}"
                )

        txn = cls(
            department_id=department_id,
            source_type=source_type,
            source_record_id=source_record_id,
            source_reference=source_reference,
            emission_factor_id=emission_factor.id,
            factor_value=emission_factor.co2e_per_unit,
            quantity=quantity,
            co2e=quantity * emission_factor.co2e_per_unit,
            transaction_date=transaction_date,
            created_by=CreatedBy.AUTO,
            status=status,
        )
        db.add(txn)
        db.flush()
        return txn
